title: PingHome
author:
  name: Ping / soowin
  email: soowindance@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  成分表：技术博客，情感博客，贴图和收藏


# Theme Settings
minima:
  social_links:
    twitter: soowindance
    github:  soowin


# Navbar Titles
header_pages:
  - questionbox.markdown
  - about.markdown


# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
